artifacts_root: artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_dir : E:\\bengla text summarization\BanSum.zip
  local_data_file : artifacts/data_ingestion/BanSum.zip
  unzip_dir : artifacts/data_ingestion

ban_tokenization:
  root_dir: artifacts/ban_tokenization
  source_dir: artifacts/data_ingestion/BanSum.csv
  save_dir: artifacts/ban_tokenization  

train_tokenize:
  root_dir : artifacts/train_tokenization
  input_file_dir : artifacts/ban_tokenization/combined_text.txt
  save_file : artifacts/train_tokenization

  

