artifacts_root: artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_dir : E:\\bengla text summarization\BanSum.zip
  local_data_file : artifacts/data_ingestion/BanSum.zip
  unzip_dir : artifacts/data_ingestion

